language: php
sudo: false
before_script:
  - composer self-update
  - composer install
  - npm install
script:
  - phpunit --verbose
matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm
  fast_finish: true
